version: '3.3'

networks:
  # création d'un nouveau réseau
  symfony:
    ipam:
      config:
        - subnet: 172.22.0.0/16
  # utilisation d'un réseau en place
  #Symfony:

services:
  # Eléments pour le container "Mariadb"
  db:
    image: mariadb:latest
    container_name: ${PROJECT}_db
    restart: ${RESTART}
    volumes:
      - ./db_data:/var/lib/mysql
    ports:
      - ${MARIA_HOST_PORT}:3306
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIA_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DBNAME}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    networks:
      symfony:
        ipv4_address: 172.22.1.1 # Mise en place d'une adresse IP_V4 fixe pour le container
  
  # Eléments pour le Container "PhpMyAdmin"
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: ${PROJECT}_pma
    restart: ${RESTART}
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      MARIA_ROOT_PASSWORD: ${MARIA_ROOT_PASSWORD}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    networks:
      symfony:
        ipv4_address: 172.22.1.2 # Mise en place d'une adresse IP_V4 fixe pour le container

  # Elements de build pour le container serveur web
  www:
    build: php
    container_name: ${PROJECT}_www
    ports:
      - ${HTTP_HOST_PORT}:80
    volumes:
      - ./php/vhosts:/etc/apache2/sites-enabled
      - ./:/var/www/html
    restart: ${RESTART}
    networks:
      symfony:
        ipv4_address: 172.22.1.3 # Mise en place d'une adresse IP_V4 fixe pour le container

